### ISSUE TITLE
Hardware triggering

### ISSUE THREAD

**Issue by MorganMasters** [FraunhoferIOSB/camera_aravis2#39]
Hi, Camera_Aravis Team,

I am working on getting a FLIR BlackFly camera (BFLY-PGE-23S6C-C) to trigger an InertialSense INS (RUG-3-IMX-5-Dual) inertial device on image capture. Currently, I have the vendor-provided software configured to perform this triggering behavior. The next step is to automatically configure the GigE camera like:

`GError *local_error = NULL;`
`//Set the output strobe`
`arv_camera_set_string (camera, "LineSelector", "Line1", &local_error);`
`arv_camera_set_string (camera, "LineMode", "Strobe", &local_error);`

The above uses the functions of the `AravisProject` SDK, in the template format of the `aravis-c-examples` [repo](https://github.com/AravisProject/aravis-c-examples/tree/main); see my attached code for the full example (lines 92-95 are where the above code snippet originated).
[06-multiple-gpio-strobe.txt](https://github.com/user-attachments/files/17346388/06-multiple-gpio-strobe.txt)

My question is simply where you would say that code snippet fits best in your ROS2 architecture, or how I would otherwise issue these commands to your ROS2 node.

Many thanks, and all the best.

**Comment by MorganMasters** [comment]
Would you consider it wiser to simply set a new GeniCam UserSet, instead of having ROS2 do on-the-fly configurations?

**Comment by MorganMasters** [comment]
Or perhaps through `SetStringFeatureValue.srv`?

**Comment by boitumeloruf** [comment]
Hi @MorganMasters,

the simplest and quickest way for you would be to set a new UseSet for the camera.

If you would like to let camera_aravis set it on the fly, one would have to introduce a new parameter set named 'DigitalIoControl'. since according doe the GenICam SFNC the 'LineSelector' is within this feature group. For the implementation the 'AnalogControl' could be used as a template. Because for setting balance ratios for the white balancing, the correct use of the corresponding selectors is also needed.

**Comment by MorganMasters** [comment]
That is exactly the input I was looking for - many thanks!
