### ISSUE TITLE
add debug version of `ASSERT_SUCCESS` & `ASSERT_SUCCESS_AND_SHUTDOWN`

### ISSUE THREAD

**Issue by rursprung** [FraunhoferIOSB/camera_aravis2#46]
as mentioned in #45 `ASSERT_SUCCESS` & `ASSERT_SUCCESS_AND_SHUTDOWN` currently are not technically assertions, they just `return` instead.
i'd propose that at least in debug builds they trigger an actual assertion (and thus immediate termination of the node). this can help with catching errors.

**Comment by boitumeloruf** [comment]
With #56 I have now implemented a suggestion to enhance the assertions and improve the error messages in order to find errors more quickly.

In combination with the changes done in #55 (Added failure codes to nodes) a node will now print the following error if an assertion fails in the constructor and, thus, the node not being fully initialized:

```bash
ros2 run camera_aravis2 camera_xml_exporter 
[FATAL] [1733478725.623502195] [camera_xml_exporter]: No cameras detected.
[FATAL] [1733478725.623924222] [camera_xml_exporter]: /home/ws/src/camera_aravis2/camera_aravis2/src/camera_xml_exporter.cpp:52: Assertion on success of 'discoverAndOpenCameraDevice()' failed
[INFO] [1733478725.625618217] [camera_xml_exporter]: Node has shut down.
[ros2run]: Process exited with failure 1
```

I have also tried swapping the 'custom' assertion with the `assert` function from the stdlib, but somehow this leads to error messages that are even less descriptive: 

```bash
ros2 run camera_aravis2 camera_xml_exporter 

** (process:43565): CRITICAL **: 09:59:31.892: arv_camera_get_string: assertion 'ARV_IS_CAMERA (camera)' failed

** (process:43565): CRITICAL **: 09:59:31.892: arv_camera_get_string: assertion 'ARV_IS_CAMERA (camera)' failed

** (process:43565): CRITICAL **: 09:59:31.892: arv_camera_get_device_serial_number: assertion 'ARV_IS_CAMERA (camera)' failed

** (process:43565): CRITICAL **: 09:59:31.892: arv_camera_get_string: assertion 'ARV_IS_CAMERA (camera)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
[ros2run]: Aborted
```

I have also refrained from calling `std::abort()`, as in my opinion an abortion of a program should happen when an unexpected error (a bug rather than a bad input) occurs.

**Comment by rursprung** [comment]
i think this comes from a difference in what is being called "assert" in this repository and what "assert" is usually being used for: here it's a general control-flow construct and it's perfectly ok for an assertion to fail (it fails due to a user error - e.g. not plugging in the camera). usually an assertion is used to verify that an invariant is being upheld (e.g. you assert that a pointer is valid) and if that contract is violated it points to a programming error in which case the continuation of the program is compromised and crashing is the only valid option.

related (but currently not an option due to compiler support being too new):
being a big fan of [Rust](https://rust-lang.org) and its [`std::result::Result`](https://doc.rust-lang.org/std/result/) i'm happy to see [`std::expected`](https://en.cppreference.com/w/cpp/utility/expected) in C++23, though its usage is still more cumbersome than its inspiration in Rust. in the (far) future (whenever you decide to drop support for compilers not supporting C++23) you might want to migrate to that.
